### ISSUE TITLE
Error when trying to run webchat 

### ISSUE THREAD

**Issue by samail** [botpress/tutorial#1]
Hi, 

I've cloned the repo and deployed step-1 on heroku server. Everything is working properly within GUI etc.
But when i try to run a simple index.html file that embed the webchat, i always get the following error : 
"Module $platform-webchat with view $embedded not found"

Got several error in console such as : 
Uncaught TypeError: React.createClass is not a function
    at Object.botpress.botpress-platform-webchat.Object.defineProperty.value

Any idea what could be wrong ? is this because of "botpress-platform-webchat" ? 

Thanks in advance 
Best

**Comment by slvnperron** [comment]
Hi Sam, yes please use the new channel-web module. Have a look at step-6
dependencies, which are up to date.

We actually have to update deps in step1 to 5.

Let me know if that works?

**Comment by samail** [comment]
Hey, 

Thx for your quick reply. 
Tested and indeed step6 is working as expected :) 

Close this issue then.
Best
