### ISSUE TITLE
Can't start the sample

### ISSUE THREAD

**Issue by Gh0s7** [botpress/tutorial#2]
I'm following the basic steps after cloning this repository, however, after running `npm start`, I get an error message saying: 

> Error: Missing required botpress setting: botUrl

These are the steps I've ran:

1. `git clone https://github.com/botpress/tutorial.git`
2. `cd tutorial`
3. `cd step-1`
4. `npm install`
5. `npm start`

I was able to start a fresh project after `bp init`, but I can't run the tutorial.

**Comment by slvnperron** [comment]
@Gh0s7 Is that working now for you with the latest code base?

**Comment by Gh0s7** [comment]
Sorry for the delay.
It works, but I think you're missing botUrl for the other steps as it looks like that step1 is the only one that got fixed.

Thanks.
